### ISSUE TITLE
Allow specifying path to service account key in connection string

### ISSUE THREAD

**Issue by tswast** [mxmzdlv/pybigquery#14]
Setting environment variables can be difficult ( see https://github.com/apache/incubator-superset/issues/945#issuecomment-384769951 ). An optional addition to the connection string to specify a path to a service account key could be very helpful.

See: https://cloud.google.com/bigquery/docs/authentication/service-account-file#loading_credentials_from_a_file

**Comment by mxmzdlv** [comment]
Agree, I'll look into this.

**Comment by mxmzdlv** [comment]
Implemented:

https://github.com/mxmzdlv/pybigquery/blob/master/pybigquery/sqlalchemy_bigquery.py#L105-L110
