### ISSUE TITLE
Dataset location

### ISSUE THREAD

**Issue by fueltank34** [mxmzdlv/pybigquery#21]
Is it possible to manually specify dataset location? Datasets in Asia are not found otherwise.

**Comment by mxmzdlv** [comment]
@fueltank34 please update to the latest version of pybigquery (0.4.2). You can now specify the location by passing location parameter:
```
engine = create_engine('bigquery://project', location="asia-northeast1")
```

If you are using Superset, you need to add the location to Extra in the Database configuration:

![screen shot 2018-08-25 at 3 42 00 pm](https://user-images.githubusercontent.com/6452112/44614684-8b861a00-a87d-11e8-8a21-a070b6b68655.png)

**Comment by fueltank34** [comment]
@mxmzdlv thanks. Do I need to do both or just one or the other?

**Comment by mxmzdlv** [comment]
For Superset just change the database configuration and you'll be good to go.
