### ISSUE TITLE
Support for <Python 3.3

### ISSUE THREAD

**Issue by mmontag** [mxmzdlv/pybigquery#3]
Hi - seems like you removed __init__.py and also start calling super() with no arguments - this breaks for Python 2.7. This broke our Superset installation :) 

I have a working fix, let me know if you would like me to submit a PR myself.

Thanks
Matt (+ Jon & Samuel at Spotify San Francisco)

**Comment by mxmzdlv** [comment]
My bad. If you could submit the PR, that would be awesome. Thanks.

**Comment by mxmzdlv** [comment]
This should be fixed now. Thanks for reporting!
