### ISSUE TITLE
Base.metadata.create_all not mapping to correct data type

### ISSUE THREAD

**Issue by Neob91** [mxmzdlv/pybigquery#31]
Hello,

I'm trying to create tables in bigquery using `Base.metadata.create_all(engine)`, however what I'm getting is:

```
google.cloud.bigquery.dbapi.exceptions.DatabaseError: 400 GET https://www.googleapis.com/bigquery/v2/projects/REDACTED/queries/REDACTED?maxResults=0&location=US: Type not found: INTEGER at [3:15]
```

Looks like sqlalchemy columns aren't correctly mapped to the BigQuery SQL data type names.
Any suggestions?

**Comment by mxmzdlv** [comment]
Currently we only support select statements. Basic DML (insert, update) should work too, although it is not tested thoroughly.

**Comment by mxmzdlv** [comment]
#32 adds generic types

We are still missing ARRAY and STRUCT, but tables with generic types can be created now.

**Comment by tswast** [comment]
Closing in favor of https://github.com/mxmzdlv/pybigquery/issues/37 to track STRUCT and ARRAY support.
