### ISSUE TITLE
403 Exceeded rate limits: too many table update operations for this table.

### ISSUE THREAD

**Issue by michaelfresco** [mxmzdlv/pybigquery#34]
I'm using the `pandas.to_sql` method to insert some data in big query. When I insert more than 30 items, (10 rows, with 3 columns), I get this error:

`"403 Exceeded rate limits: too many table update operations for this table."`

Ps: apologies, if this is more of a user support question, rather than a real bug or issue.

**Comment by michaelfresco** [comment]
Misunderstood product. Closing now.

**Comment by tswast** [comment]
In case someone else lands here with the same question: [BigQuery has strict limits on the number of DML statements](https://cloud.google.com/bigquery/quotas#data_manipulation_language_statements) per project (and table) per day.

It's recommended that you upload your data in bulk using load jobs. Or if appending rows one at a time, use the streaming API.
