### ISSUE TITLE
 Did not recognize type 'RECORD' , looking to analytcs sessions in bigquery

### ISSUE THREAD

**Issue by robyinno** [mxmzdlv/pybigquery#4]
/site-packages/pybigquery/sqlalchemy_bigquery.py:144: SAWarning: Did not recognize type 'RECORD' of column 'hits'

**Comment by mxmzdlv** [comment]
Unfortunately, RECORD/STRUCT type is not support at the moment. As a workaround, you can create a BigQuery view with a flattened schema for now.

**Comment by sumedhsakdeo** [comment]
Is there plan to add support for RECORD type in near future? If you don't mind, I can find some time to contribute the support for RECORD type.

**Comment by sumedhsakdeo** [comment]
Could lack of this, be the reason why I cannot add tables that contain RECORD type to superset?

**Comment by mxmzdlv** [comment]
Hi @sumedhsakdeo 

Yes, that would most likely be a problem. I haven't dug deep into this, as creating a view with a flattened schema and using that as a table worked for me in the past.

You are most certainly welcome to work on this, it would be a much needed feature!

**Comment by tswast** [comment]
There shouldn't be anything preventing this in the `google-cloud-bigquery` DB-API layer, as it converts to dictionaries when reading results of RECORD columns.

<details>
<summary>Expand for the whole conversion chain.</summary>

The DB-API calls `list_rows()` on the query results table at

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b8b28b15ebb47461e8c302ecd57d87741211ad10/bigquery/google/cloud/bigquery/dbapi/cursor.py#L191-L198

which returns a RowIterator

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b8b28b15ebb47461e8c302ecd57d87741211ad10/bigquery/google/cloud/bigquery/table.py#L1099

Which converts the API response to Python objects with `_row_tuple_from_json`

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b8b28b15ebb47461e8c302ecd57d87741211ad10/bigquery/google/cloud/bigquery/_helpers.py#L196-L220

Which converts to dictionaries for record types.

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b8b28b15ebb47461e8c302ecd57d87741211ad10/bigquery/google/cloud/bigquery/_helpers.py#L155-L167

</details>

One caveat, is that query parameters containing struct values are not yet supported at the DB-API layer. Feature request at https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3524

**Comment by sumedhsakdeo** [comment]
@tswast thanks for the pointers. Looks like the feature request is still TODO. Is there any plans to fix in near future?

We're using Apache Superset for visualization which is using pybigquery to connect to BigQuery. We are not able to add BQ tables to the Superset that have complex nested and repeated fields, and hence no visualization for these.

We're able to add BQ tables that do not contain these types, and visualize data.

**Comment by sumedhsakdeo** [comment]
My guess is even schema for the table with nested fields is not returned correctly?

**Comment by tswast** [comment]
@sumedhsakdeo That issue is for query parameter support, which I believe should not be required for the initial SQLAlchemy implementation in this library.
