### ISSUE TITLE
Default dataset feature does not work with google-cloud-bigquery 1.22.0

### ISSUE THREAD

**Issue by alonme** [mxmzdlv/pybigquery#43]
Hi,

It seems that creating an engine with a default dataset like in the readme example 
`engine = create_engine('bigquery://project/dataset')`

Does not work with the newest version of the bigquery library -  1.22.0.

When trying to perform a query:
`sqlalchemy.exc.DatabaseError: (google.cloud.bigquery.dbapi.exceptions.DatabaseError) 400 Table name "my_table_name" missing dataset while no default dataset is set in the request.`

Works fine with:
* Version 1.21.0
* Using the dataset as a prefix to the table name

Thanks!

**Comment by tswast** [comment]
I thought this might be a regression in `google-cloud-bigquery`, but I'm unable to reproduce with either the `query()` method or the DB-API.

```python
from google.cloud import bigquery


print(bigquery.__version__)

default_config = bigquery.QueryJobConfig(
    default_dataset="bigquery-public-data.usa_names"
)

client = bigquery.Client(default_query_job_config=default_config)


sql = """
SELECT name, SUM(number) as total_people
FROM usa_1910_2013
WHERE state = 'TX'
GROUP BY name, state
ORDER BY total_people DESC
LIMIT 5
"""

rows = client.query(sql, job_config=bigquery.QueryJobConfig(use_legacy_sql=False))

print("with query():")
for row in rows:
    print(row["name"])


from google.cloud.bigquery import dbapi

connection = dbapi.connect(client=client)
cursor = connection.cursor()

print("with dbapi:")
cursor.execute(sql)
rows = cursor.fetchall()

for row in rows:
    print(row[0])
```

Output:

```
1.22.0
with query():
James
John
Michael
Robert
David
with dbapi:
James
John
Michael
Robert
David
```

**Comment by alonme** [comment]
Please assign to me, started working on resolving the issue.

**Comment by winstonll** [comment]
> Please assign to me, started working on resolving the issue.

Thanks, I am having similar issues too. Look forward to your solution.

**Comment by alonme** [comment]
Opened a PR
https://github.com/mxmzdlv/pybigquery/pull/32
