### ISSUE TITLE
Type synonyms not exported to top-level module

### ISSUE THREAD

**Issue by jcampbell** [mxmzdlv/pybigquery#46]
The sqlalchemy docs state that:

> As with all SQLAlchemy dialects, all UPPERCASE types that are known to be valid with PostgreSQL are importable from the top level dialect, whether they originate from sqlalchemy.types or from the local dialect

However, the pybigquery dialect currently does not allow importing known valid types. I believe the dialect should explicitly import valid bigquery types to the top level so that it conforms to this standard.

Concretely, I believe the following should work:
from pybigquery.sqlalchemy_bigquery.BigQueryDialect import RECORD (and same for all bigquery types)

Sqlalchemy docs ref: https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#postgresql-data-types

It appears to be as simple as exposing the `_type_map` dictionary publicly--would that be a welcome PR?

**Comment by mxmzdlv** [comment]
Sorry for the delay! This would certainly be welcome, thanks!

**Comment by jcampbell** [comment]
Thank you! I just created #50
