### ISSUE TITLE
project_id is ignored when using service account with different project id

### ISSUE THREAD

**Issue by mindartur** [mxmzdlv/pybigquery#48]
Whatever options is used, can't override project ID from service account

**Comment by tswast** [comment]
Looks like we need to update https://github.com/mxmzdlv/pybigquery/blob/1a76103a445de6ad9bb329346ecf075d1255a118/pybigquery/sqlalchemy_bigquery.py#L303 to pass the `url.host` to `self._create_client_from_credentials`.

Pull requests welcome.

**Comment by alonme** [comment]
@tswast we can resolve this issue, as it is now merged in available in the release

**Comment by tswast** [comment]
I add some unit tests for this in https://github.com/googleapis/python-bigquery-sqlalchemy/pull/100
