### ISSUE TITLE
Client.dataset is deprecated

### ISSUE THREAD

**Issue by dimkonko** [mxmzdlv/pybigquery#58]
Raised on this line: https://github.com/mxmzdlv/pybigquery/blob/master/pybigquery/sqlalchemy_bigquery.py#L380

```
Client.dataset is deprecated and will be removed in a future version.
Use a string like 'my_project.my_dataset' or a "
cloud.google.bigquery.DatasetReference object, instead.
```

We can use `client.get_table("dataset.table")` directly.

I wanted to create a PR but looks lite writes are restricted in this repo.

**Comment by tswast** [comment]
Thanks for bringing this up. I agree that using `get_table` with a string (and project argument) is the most straightforward solution, but might actually need to use [TableReference.from_string("dataset.table", default_project=project)](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.table.TableReference.html#google.cloud.bigquery.table.TableReference) to support project overrides.

@dimkonko you should be able to [create a PR from a fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by dimkonko** [comment]
Thank you for a quick response. Make sense. I'll take a look later today.

**Comment by dimkonko** [comment]
PR with a fix was merged so closing the issue. Thank you for support.
