### ISSUE TITLE
Dataset/Table/Column details missing on SQL editor

### ISSUE THREAD

**Issue by kuriancheeramelil** [mxmzdlv/pybigquery#6]
[sqlalchemy_bigquery.txt](https://github.com/mxmzdlv/pybigquery/files/1539928/sqlalchemy_bigquery.txt)
Hi,
I am using pybigquery with superset. The dataset/table/column details was missing in the sql editor dropdown list. Did some changes to pybigquery/sqlalchemy_bigquery.py and it seems to working now. The dataset, table and column definitions are getting listed.
I am not sure if the fix is complete. If possible could you review it. I have attached the edited file.

Versions of superset and pybigquery used
Name: superset
Version: 0.20.6

Name: pybigquery
Version: 0.2.3

**Comment by mxmzdlv** [comment]
Thanks! The code looks good. I'll merge it sometime next week and if it is all good — will push it in the next release.
I was on the fence about whether to treat datasets as schemas, but if superset relies on schemas in their interface — the library really should support it.

**Comment by kuriancheeramelil** [comment]
Ok 👍
Thank you @mxmzdlv

**Comment by mxmzdlv** [comment]
Pushed the fix in 0.2.5. Thanks for your contribution!

**Comment by kuriancheeramelil** [comment]
You are welcome.
