### ISSUE TITLE
No mention of authentication

### ISSUE THREAD

**Issue by darylerwin** [mxmzdlv/pybigquery#9]
Any info on what needs to be installed prior to running this to authenticate? Perhaps cloud sdk or gcloud authenticate?

**Comment by mxmzdlv** [comment]
Easiest way is to install Google Cloud SDK. [This guide](https://googlecloudplatform.github.io/google-cloud-python/latest/core/auth.html) from Google should help.

**Comment by darylerwin** [comment]
Yes .. got this with the installation of the google sdk and the authentication and json files.
